### ISSUE TITLE
SOQL select order should match with columns definition order

### ISSUE THREAD

**Issue by nahi** [treasure-data/embulk-input-sfdc#23]
I expected the following definition stores Id, Name, and CreatedDate to id_, _name, and created_date respectively. It's my understanding that now embulk-input-sfdc stores column values based on name.

Does it sound feasible?
```
---
in:
  type: sfdc
  target: Account
  soql: SELECT Id,Name,CreatedDate
    FROM Account
  columns:
  - name: id_
    type: string
  - name: _name
    type: string
  - name: created_date
    type: timestamp
    format: "%Y-%m-%dT%H:%M:%S.%L%z"
out:
  mode: replace
```
